version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - pip install --user aws-sam-cli
      - export PATH=$PATH:/root/.local/bin
      - sam --version
      - npm i -g npm@latest
      - npm install
      - npx webpack --config build/webpack.client.config.js
      - npx webpack --config build/webpack.server.config.js
      - mv node_modules ./dependencies/nodejs/
      - sam build
      - sam package --s3-bucket listman-s3-bucket --output-template-file output.yaml
      - sam deploy --template-file output.yaml --stack-name listman --capabilities CAPABILITY_IAM 


#      - export BUCKET=listman-prod-artifact
#      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
#artifacts:
#  type: zip
#  files:
#    - template.yaml
#    - outputtemplate.yaml