version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - pip install --user aws-sam-cli
      - export PATH=$PATH:/root/.local/bin
      - sam --version
      - npm i -g npm@latest @aws-amplify/cli
      - echo "Installing node modules for layer..."
      - cd dependencies/nodejs/
      - npm install
      - cd ../..
      - echo "Installing node modules for webpack..."
      - npm install
      - export AMPLIFY="{\"awscloudformation\":{\"configLevel\":\"project\",\"useProfile\":\"false\",\"profileName\":\"default\",\"accessKeyId\":\"${AMPLIFY_ID}\",\"secretAccessKey\":\"${AMPLIFY_SECRET}\",\"region\":\"us-east-1\"}}"
      - echo $AMPLIFY
      - aws --version
      - amplify init --amplify "{\"envName\":\"prod\"}" --providers $AMPLIFY --yes
      - amplify env checkout prod --yes
      - cat src/aws-exports.js
      - npx webpack --config build/webpack.client.config.js
      - npx webpack --config build/webpack.server.config.js
      - echo "Running sam build, package and deploy..."
      - sam build
      - rm -rf .aws-sam/build/SSRFunction/node_modules
      - sam package --s3-bucket listman-package --output-template-file output.yaml
      - sam deploy --template-file output.yaml --stack-name listman --capabilities CAPABILITY_IAM 


#      - export BUCKET=listman-prod-artifact
#      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
#artifacts:
#  type: zip
#  files:
#    - template.yaml
#    - outputtemplate.yaml