version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - pip install --user aws-sam-cli
      - export PATH=$PATH:/root/.local/bin
      - sam --version
      - npm i -g npm@latest @aws-amplify/cli
      - echo "Installing node modules for layer..."
      - cd dependencies/nodejs
      - npm install
      - cd node_modules/gaxios
      - npm install node-fetch@2.2.0
      - cd ../..
      - cd ../..
      - echo "Installing node modules for webpack..."
      - npm install
      - echo "Initializing amplify..."
      - mkdir ~/.aws
      - echo "[default]" > ~/.aws/credentials
      - echo "aws_access_key_id=$AMPLIFY_ID" >> ~/.aws/credentials
      - echo "aws_secret_access_key=$AMPLIFY_SECRET" >> ~/.aws/credentials
      - echo "[default]" > ~/.aws/config
      - echo "region=us-east-1" >> ~/.aws/config
      - amplify init --amplify "{\"envName\":\"prod\"}" --yes
      - amplify env checkout prod
      - cat src/aws-exports.js
      - echo "Building client/server bundles..."
      - npx webpack --config build/webpack.client.config.js
      - npx webpack --config build/webpack.server.config.js
      - npx node-sass --omit-source-map-url sass/bulma.scss dist/css/bulma.css
      - aws s3 cp dist/ s3://listman-dist/ --recursive
      - echo "Running sam build, package and deploy..."
      - sam build
      - rm -rf .aws-sam/build/SSRFunction/node_modules
      - sam package --s3-bucket listman-package --output-template-file output.yaml
      - sam deploy --template-file output.yaml --stack-name listman --capabilities CAPABILITY_IAM 


#      - export BUCKET=listman-prod-artifact
#      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
#artifacts:
#  type: zip
#  files:
#    - template.yaml
#    - outputtemplate.yaml